FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt .
RUN pip install --no-cache-dir --timeout=120 --retries=5 -r requirements-frontend.txt

COPY app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]